// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bdaya/social_training/v1/service.proto
// </auto-generated>
namespace Google
{
    internal class Api
    {
    }
}